name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Copy build to public_html
        run: |
          rm -rf public_html/*
          cp -r build/* public_html/
          # Remove source maps from public_html before committing
          rm -f public_html/static/**/*.map

      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f public_html
          git commit -m "chore: update production build"
          git push